### ISSUE TITLE
Item costs more than it should

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#1]
In this example, the cost should be $2,300 but it reports it as $4,200 and takes that amount from my total money.
Here is the output it gives,
Simple Infused Focus Item

A basic focus item, but it also provides an attack. Type Differs per cabalist (kinetic/cold/fire/electric/meta)

Monetary Cost: $$4200
Details
    Firebolt: ($$ 1900)
    Magic: Magic ($$ 200)
    Accuracy Modifier: +1 Attack Accuracy ($$ 200)

Code below.
```
- name: Simple Infused Focus Item
      text: A basic focus item, but it also provides an attack. Type Differs per cabalist (kinetic/cold/fire/electric/meta)
      grants:
       - Firebolt
      rules:
       Accuracy Modifier: +1 Attack Accuracy
       Magic: Magic
```

**Comment by zinic** [comment]
Ha. This was due to the formatting code (not the checking code) calculating aspect grants separate of the actual item cost breakdown and adding both results.

See https://github.com/zinic/crawl/commit/c98476ef0605b66762d22cba3bca05e0a7545699
