### ISSUE TITLE
"require" does not affect aspects

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#6]
Was having a difficult time finding a good title for this, but basically if you make an aspect require another one, it neither posts this dependency in the aspect itself nor does it complain if the required aspect is missing.

Example code below,

```
---

character:
  name: Some creature
  aspect_points: 200
  starting_funds: 0

  items:
    - name: Let me build a character
  aspects:
    - name: Slash

    - name: Something something
      template: Attack
      text: meta description
      require: Slash
      skill:
       type: Attack
       inherits:
       - Mobility
      rules:
       Damage: 1d10
       Damage Type: Kinetic
       Failure Chance: Difficulty 10
       Range: Melee
       Energy Point Cost: "+1"
```

**Comment by zinic** [comment]
The name for `require` was originally `requirements` but it got lost somewhere during refactoring. I've fixed this up: https://github.com/zinic/crawl/commit/e02d9f4bfa175b5496a8ec522541eabb3d15447a#diff-14fd6316e5d08094303ca7295afe8877L464
