### ISSUE TITLE
In output.md Energetic does not define action

### ISSUE THREAD

**Issue by Sedohr** [zinic/crawl#8]
In the output.md "Energetic" exotic type does not clarify what it does, just how it works.

The document states,
`Energetic damage types are very effective but also chaotic. Upon a successful hit the attacker may roll a fate die. Negative and neutral values have no additional effect.`
It seems like after the fate dice it would clarify what it does, but all it says that neutral and negative have no effect.

**Comment by zinic** [comment]
Bad Hopper, no dice. Updated the doc: https://github.com/zinic/crawl/commit/883a11c20a58d00a135b0be87582ff6ed6041f61
